-- Migration 029: Public parent-registration support.
--
-- Adds the surface area the new "/torneo/:slug/inscripcion" public form
-- needs so an acudiente (parent) can enroll a jugadora into a club's
-- team without an admin/captain login:
--
--   · tournaments.slug
--       Per-tournament public URL fragment. Backfilled with
--       kebab(name) + 6-char id suffix to guarantee uniqueness across
--       multi-admin tenants (Admin A's "Copa 2026" and Admin B's
--       "Copa 2026" land on distinct slugs). New tournaments get their
--       slug generated by tournament.service on insert.
--
--   · players.birth_date
--       Full date of birth replacing the old INT `birth_year`. Public
--       parent flow asks for a full date, and the admin/captain UI
--       gains a calendar picker. Existing rows are backfilled with
--       `YYYY-01-01` from birth_year and the old column is dropped at
--       the end of this migration — front + back move to birth_date
--       in lockstep.
--
--   · players.emergency_contact_{name,phone,relationship}
--       Single emergency contact captured by the parent form (and
--       editable later from the admin / captain panel). The school /
--       hospital scenario the org cares about only needs one number;
--       we'd add a second contact later if user feedback demands it.
--
--   · players.registered_via_public
--       Audit flag so the panel can badge / filter jugadoras that came
--       in through the parent form vs. the manual admin/captain entry.
--       FALSE for every legacy row and every record created from the
--       admin / captain modals.

-- ── tournaments.slug ──────────────────────────────────────────────
ALTER TABLE tournaments
  ADD COLUMN IF NOT EXISTS slug VARCHAR(160);

-- Backfill: kebab(name) + 6-char id suffix.
--   · regexp_replace #1 collapses any non-alphanumeric run into '-'
--   · regexp_replace #2 trims leading / trailing dashes
--   · lower() so the URL is case-insensitive
--   · `substring(id::text, 1, 6)` is 6 hex chars (≈16M combos) so
--     collisions are astronomically unlikely even with 1000+ tornos
--     sharing the same name. Plenty of margin for the UNIQUE index
--     below not to trip on the backfill.
-- Accents are stripped naively (turned into '-') — losing the visual
-- nuance is fine because the suffix is the uniqueness driver. New
-- tournaments will use a proper unicode-normalized slug from the
-- service layer.
UPDATE tournaments
SET slug = (
  lower(
    regexp_replace(
      regexp_replace(name, '[^A-Za-z0-9]+', '-', 'g'),
      '(^-+|-+$)', '', 'g'
    )
  ) || '-' || substring(id::text, 1, 6)
)
WHERE slug IS NULL;

-- Enforce NOT NULL + UNIQUE after the backfill so existing rows pass.
ALTER TABLE tournaments
  ALTER COLUMN slug SET NOT NULL;
CREATE UNIQUE INDEX IF NOT EXISTS tournaments_slug_key
  ON tournaments (slug);

-- ── players: birth_date + emergency contact + audit ──────────────
ALTER TABLE players
  ADD COLUMN IF NOT EXISTS birth_date DATE,
  ADD COLUMN IF NOT EXISTS emergency_contact_name VARCHAR(160),
  ADD COLUMN IF NOT EXISTS emergency_contact_phone VARCHAR(40),
  ADD COLUMN IF NOT EXISTS emergency_contact_relationship VARCHAR(80),
  ADD COLUMN IF NOT EXISTS registered_via_public BOOLEAN NOT NULL DEFAULT FALSE;

-- Backfill birth_date from birth_year. Jan 1st is a placeholder — the
-- admin / captain can re-enter the exact date next time they touch the
-- jugadora. Skip rows where birth_year is null or birth_date is already
-- set so re-running this migration locally is idempotent.
UPDATE players
SET birth_date = make_date(birth_year, 1, 1)
WHERE birth_year IS NOT NULL AND birth_date IS NULL;

-- Drop the legacy column. The frontend's PlayerFormModal, the
-- TeamRosterCard's row metadata, and the player.service all switch to
-- birth_date in the same release that ships this migration.
ALTER TABLE players DROP COLUMN IF EXISTS birth_year;

-- ── push_subscriptions: club_id ───────────────────────────────────
-- Club captains (mig 028 principals) authenticate via username +
-- password but they don't have a row in `users` — clubs are a parallel
-- auth principal. That means a club captain subscribing to web push
-- writes the row with `user_id = NULL`, and the existing
-- `sendToUser(userId, …)` helper can't reach them.
--
-- Adding `club_id` lets us index push subs by their owning club so
-- the public parent-registration endpoint can ping ONLY the captains
-- of the club the parent just submitted to (vs broadcasting to every
-- subscriber, which sendToAll would do). The column is nullable
-- because regular admin / spectator subs don't have a club.
ALTER TABLE push_subscriptions
  ADD COLUMN IF NOT EXISTS club_id UUID
    REFERENCES clubs(id) ON DELETE CASCADE;

CREATE INDEX IF NOT EXISTS push_subscriptions_club_id_idx
  ON push_subscriptions(club_id);
