import { Outlet, useNavigate } from 'react-router';
import { LogOut, Users } from 'lucide-react';
import { useAuth } from '../context/AuthContext';

/**
 * TeamPanelLayout — shell for the `team_captain` role. Captains log in with
 * credentials generated by an admin (see TeamCredentialsModal) and land here
 * to manage their own roster, gated by the tournament's enrollment_deadline
 * in future iterations. Visually lighter than JudgeLayout (white chrome,
 * not a live-scoring console) because captains spend time filling forms,
 * not reacting to the live scoreboard.
 */
export function TeamPanelLayout() {
  const { user, logout } = useAuth();
  const navigate = useNavigate();

  const handleLogout = async () => {
    await logout();
    navigate('/login', { replace: true });
  };

  return (
    <div className="min-h-screen bg-white text-spk-black flex flex-col">
      <header className="sticky top-0 z-30 bg-white/95 backdrop-blur-md border-b border-black/10">
        <div className="max-w-[1200px] mx-auto px-4 sm:px-6 md:px-10 h-16 flex items-center justify-between">
          <div className="flex items-center gap-3 min-w-0">
            <div className="w-9 h-9 rounded-sm bg-spk-red flex items-center justify-center flex-shrink-0">
              <Users className="w-4 h-4 text-white" aria-hidden="true" />
            </div>
            <div className="leading-tight min-w-0">
              <div
                className="text-base sm:text-lg font-bold uppercase tracking-tighter truncate"
                style={{ fontFamily: 'Barlow Condensed, sans-serif' }}
              >
                Torny · Panel de Equipo
              </div>
              <div className="text-[11px] text-black/55 uppercase tracking-[0.16em] truncate">
                {user?.username ?? 'Capitán'}
              </div>
            </div>
          </div>
          <button
            type="button"
            onClick={handleLogout}
            className="inline-flex items-center gap-2 px-3 sm:px-4 py-2 bg-black/5 hover:bg-black/10 border border-black/10 rounded-sm text-xs sm:text-sm font-bold uppercase tracking-wider transition-colors"
            style={{ fontFamily: 'Barlow Condensed, sans-serif' }}
          >
            <LogOut className="w-4 h-4" />
            <span className="hidden sm:inline">Cerrar sesión</span>
          </button>
        </div>
      </header>
      <main className="flex-1">
        <Outlet />
      </main>
    </div>
  );
}
