import { getPool } from '../config/database';
import {
  Match,
  SetScore,
  CreateMatchDto,
  UpdateMatchDto,
  ScoreUpdate,
  ValidationResult,
} from '../types';
import { NotFoundError, ValidationError } from '../middleware/errorHandler';
import { validate } from '../middleware/validation';
import { standingsCalculator } from './standings.service';
import { bracketGenerator } from './bracket.service';
import { fixtureGenerator } from './fixture.service';
import { pushService, ensureReady as ensurePushReady } from './push.service';

/**
 * Fire-and-forget helper that builds the two-team label used in push
 * titles. Falls back to "Partido" when we couldn't join the team
 * rows (shouldn't happen but a push should never fail a match write).
 */
async function matchHeadline(matchId: string): Promise<{ title: string; url: string }> {
  const pool = getPool();
  const result = await pool.query(
    `SELECT m.id, m.tournament_id,
            t1.name AS t1_name, t1.initials AS t1_initials,
            t2.name AS t2_name, t2.initials AS t2_initials
     FROM matches m
     LEFT JOIN teams t1 ON m.team1_id = t1.id
     LEFT JOIN teams t2 ON m.team2_id = t2.id
     WHERE m.id = $1`,
    [matchId],
  );
  if (result.rows.length === 0) {
    return { title: 'Partido', url: '/' };
  }
  const row = result.rows[0];
  const team1 = (row.t1_name as string) || (row.t1_initials as string) || 'Equipo 1';
  const team2 = (row.t2_name as string) || (row.t2_initials as string) || 'Equipo 2';
  return {
    title: `${team1} vs ${team2}`,
    url: `/match/${matchId}`,
  };
}

/**
 * Resolve the DISTINCT clubs whose teams participate in a given
 * match. The list drives the per-club push notifications fired
 * after score / status / schedule changes (mig 028 + 2026-05-13).
 *
 * Two teams that belong to the same club collapse into one entry
 * (DISTINCT) so a club captain never gets the same notif twice for
 * a derby. Teams without a club_id are skipped silently — there's
 * no audience to notify.
 *
 * Returns an empty array on any failure so callers can spread the
 * result safely in a `try/catch`-wrapped push dispatch. The pushes
 * are best-effort by design.
 */
async function clubIdsForMatch(matchId: string): Promise<string[]> {
  try {
    const pool = getPool();
    const result = await pool.query<{ club_id: string }>(
      `SELECT DISTINCT t.club_id
         FROM matches m
         LEFT JOIN teams t1 ON t1.id = m.team1_id
         LEFT JOIN teams t2 ON t2.id = m.team2_id
         JOIN LATERAL (
           VALUES (t1.club_id), (t2.club_id)
         ) AS t(club_id) ON TRUE
        WHERE m.id = $1
          AND t.club_id IS NOT NULL`,
      [matchId],
    );
    return result.rows.map((r) => r.club_id);
  } catch (err) {
    console.warn('[push] clubIdsForMatch failed:', err);
    return [];
  }
}

/**
 * Fan out a single push payload to every club involved in a match.
 * Best-effort: a failure on one club must not block the others, and
 * the calling business logic (score save, schedule update) MUST NOT
 * see this throw. Wraps the loop in try/catch + logs.
 *
 * Typical payloads:
 *   · "Cambio de horario" when an admin moves a match.
 *   · "Resultado final" when a referee closes the last set.
 *   · "Set cerrado" + running score on every closing set.
 *   · "Partido en vivo" when status flips upcoming → live.
 */
async function dispatchClubsForMatch(
  matchId: string,
  payload: { title: string; body: string; url: string; tag: string },
): Promise<void> {
  try {
    const keys = await ensurePushReady();
    if (!keys) return;
    const clubs = await clubIdsForMatch(matchId);
    for (const clubId of clubs) {
      try {
        await pushService.sendToClub(clubId, payload);
      } catch (err) {
        console.warn(`[push] club ${clubId} dispatch failed`, err);
      }
    }
  } catch (err) {
    console.warn('[push] dispatchClubsForMatch failed:', err);
  }
}

/**
 * Recalculate standings and re-resolve any bracket placeholders for a
 * tournament. Called after every match mutation that could affect either.
 * Bracket re-resolution is wrapped in try/catch because it's best-effort:
 * tournaments without a bracket, or with bracket matches that have no
 * placeholders, should still succeed on the standings side.
 */
async function refreshTournamentState(tournamentId: string): Promise<void> {
  await standingsCalculator.recalculate(tournamentId);
  try {
    await bracketGenerator.resolveBracketFromStandings(tournamentId);
  } catch {
    // swallow — bracket refresh is best-effort
  }
  try {
    // Division-mode tournaments auto-seed Oro/Plata the moment every
    // group match for a category wraps up. The call is idempotent
    // (skips categories that already have a bracket), so running it
    // after every score write is safe and cheap.
    await fixtureGenerator.autoGenerateDivisionBrackets(tournamentId);
  } catch {
    // swallow — auto-bracket is best-effort, never blocks a score save
  }
  try {
    // Materialize playable matches for any bracket slot that just got
    // its two teams resolved (either by the standings re-resolution
    // above, or by a previous advanceWinner). Idempotent — only
    // creates rows for slots that don't yet have a `matches` row.
    await bracketGenerator.materializePendingBracketMatches(tournamentId);
  } catch (err) {
    console.warn('[refreshTournamentState] materialize failed:', err);
  }
}

function mapRow(row: Record<string, unknown>): Match {
  return {
    id: row.id as string,
    tournamentId: row.tournament_id as string,
    // team1_id / team2_id are now nullable for bracket slots that
    // haven't been resolved yet (mig 030). Keep the cast honest so
    // downstream code remembers to handle the placeholder case
    // instead of crashing on `team1Id.length` etc.
    team1Id: (row.team1_id as string | null) ?? null,
    team2Id: (row.team2_id as string | null) ?? null,
    date: row.date as string,
    time: row.time as string,
    court: row.court as string,
    referee: row.referee as string | undefined,
    status: row.status as Match['status'],
    scoreTeam1: row.score_team1 != null ? (row.score_team1 as number) : undefined,
    scoreTeam2: row.score_team2 != null ? (row.score_team2 as number) : undefined,
    phase: row.phase as string,
    groupName: row.group_name as string | undefined,
    duration: row.duration != null ? (row.duration as number) : undefined,
    bracketMatchId: (row.bracket_match_id as string | null | undefined) ?? null,
    createdAt: row.created_at as string | undefined,
    updatedAt: row.updated_at as string | undefined,
  };
}

function mapSetRow(row: Record<string, unknown>): SetScore {
  return {
    id: row.id as string,
    matchId: row.match_id as string,
    setNumber: row.set_number as number,
    team1Points: row.team1_points as number,
    team2Points: row.team2_points as number,
  };
}

/**
 * Context used when listing matches. Public + super_admin see everything;
 * admins see matches of their own tournaments; judges see only LIVE
 * matches from tournaments owned by the admin that created them.
 */
export type MatchListScope =
  | { scope: 'all' }
  | { scope: 'owner'; ownerId: string }
  | { scope: 'judge'; judgeCreatedBy: string };

export class MatchService {
  async getAll(scope: MatchListScope = { scope: 'all' }): Promise<Match[]> {
    const pool = getPool();
    if (scope.scope === 'judge') {
      // Judges see only live matches from tournaments owned by the admin
      // who created them. The join with tournaments is how we enforce the
      // cross-tenant isolation in a single query instead of two round-trips.
      const result = await pool.query(
        `SELECT m.* FROM matches m
         JOIN tournaments t ON m.tournament_id = t.id
         WHERE t.owner_id = $1 AND m.status = 'live'
         ORDER BY m.date, m.time`,
        [scope.judgeCreatedBy],
      );
      const matches = result.rows.map(mapRow);
      return this.attachSets(matches);
    }
    if (scope.scope === 'owner') {
      const result = await pool.query(
        `SELECT m.* FROM matches m
         JOIN tournaments t ON m.tournament_id = t.id
         WHERE t.owner_id = $1
         ORDER BY m.date, m.time`,
        [scope.ownerId],
      );
      const matches = result.rows.map(mapRow);
      return this.attachSets(matches);
    }
    const result = await pool.query('SELECT * FROM matches ORDER BY date, time');
    const matches = result.rows.map(mapRow);
    return this.attachSets(matches);
  }

  async getById(id: string): Promise<Match> {
    const pool = getPool();
    const result = await pool.query('SELECT * FROM matches WHERE id = $1', [id]);
    if (result.rows.length === 0) {
      throw new NotFoundError('Partido');
    }
    const match = mapRow(result.rows[0]);
    const sets = await this.getSets(id);
    match.sets = sets;
    return match;
  }

  async getByTournament(tournamentId: string): Promise<Match[]> {
    // Verify tournament exists
    const pool = getPool();
    const tournamentCheck = await pool.query('SELECT id FROM tournaments WHERE id = $1', [tournamentId]);
    if (tournamentCheck.rows.length === 0) {
      throw new NotFoundError('Torneo');
    }
    const result = await pool.query(
      'SELECT * FROM matches WHERE tournament_id = $1 ORDER BY date, time',
      [tournamentId]
    );
    const matches = result.rows.map(mapRow);
    return this.attachSets(matches);
  }

  async create(data: CreateMatchDto): Promise<Match> {
    await this.validateData(data);
    const pool = getPool();
    const result = await pool.query(
      `INSERT INTO matches (tournament_id, team1_id, team2_id, date, time, court, referee, phase, group_name)
       VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
       RETURNING *`,
      [
        data.tournamentId,
        data.team1Id,
        data.team2Id,
        data.date,
        data.time,
        data.court,
        data.referee || null,
        data.phase,
        data.groupName || null,
      ]
    );
    return mapRow(result.rows[0]);
  }

  async update(id: string, data: UpdateMatchDto): Promise<Match> {
    // Ensure match exists
    const existing = await this.getById(id);

    // If updating team references, validate them
    if (data.team1Id !== undefined || data.team2Id !== undefined || data.tournamentId !== undefined) {
      const mergedTeam1 = data.team1Id ?? existing.team1Id;
      const mergedTeam2 = data.team2Id ?? existing.team2Id;
      const mergedTournament = data.tournamentId ?? existing.tournamentId;

      // Only reject `team1 === team2` when BOTH ends are resolved.
      // Since mig 030 the cronograma materializes bracket slots whose
      // teams aren't known yet, so both `mergedTeam1` and `mergedTeam2`
      // can legitimately be `null` — and `null === null` is `true`,
      // which used to crash the drag-and-drop with "Los dos equipos
      // deben ser diferentes" the moment the admin tried to reschedule
      // an unresolved cuartos/semi/final.
      if (
        mergedTeam1 !== null &&
        mergedTeam2 !== null &&
        mergedTeam1 === mergedTeam2
      ) {
        throw new ValidationError('Los dos equipos deben ser diferentes');
      }

      const pool = getPool();
      if (data.tournamentId !== undefined) {
        const tCheck = await pool.query('SELECT id FROM tournaments WHERE id = $1', [mergedTournament]);
        if (tCheck.rows.length === 0) {
          throw new NotFoundError('Torneo');
        }
      }
      // Skip the team-exists check when the slot is intentionally
      // unresolved (mergedTeamX === null). Without this guard, the
      // `SELECT id FROM teams WHERE id = NULL` query returns zero rows
      // and the admin would see "Equipo 1 no encontrado" on any drag
      // that touched a bracket placeholder.
      if (data.team1Id !== undefined && mergedTeam1 !== null) {
        const t1Check = await pool.query('SELECT id FROM teams WHERE id = $1', [mergedTeam1]);
        if (t1Check.rows.length === 0) {
          throw new NotFoundError('Equipo 1');
        }
      }
      if (data.team2Id !== undefined && mergedTeam2 !== null) {
        const t2Check = await pool.query('SELECT id FROM teams WHERE id = $1', [mergedTeam2]);
        if (t2Check.rows.length === 0) {
          throw new NotFoundError('Equipo 2');
        }
      }
    }

    // Schedule conflict check — runs whenever the admin moves a match
    // (date / time / court change) OR swaps a team into a different
    // slot. We compare the would-be (date, time, team1, team2) against
    // every other match in the same tournament; if any of the four
    // pairings collide we abort with a human-readable error.
    //
    // Two failure modes we guard against:
    //   1. Same team plays two matches at the exact same date+time
    //      (the SAN JOSE A bug from 2026-05-10 — the algorithm got
    //      this right historically but a manual edit could put a team
    //      in two simultaneous matches without complaint).
    //   2. Two matches scheduled on the same court at the same date+time
    //      (court collision — physically impossible).
    //
    // Skipped only when none of the relevant fields are being touched
    // (purely a status / score / referee update) so editing scores on
    // an existing match never triggers a query just to re-confirm what
    // was already valid.
    const touchesSlot =
      data.date !== undefined ||
      data.time !== undefined ||
      data.court !== undefined ||
      data.team1Id !== undefined ||
      data.team2Id !== undefined ||
      data.tournamentId !== undefined;
    if (touchesSlot) {
      const mergedTournament = data.tournamentId ?? existing.tournamentId;
      const mergedDate = data.date ?? existing.date;
      const mergedTime = data.time ?? existing.time;
      const mergedCourt = data.court ?? existing.court;
      const mergedTeam1 = data.team1Id ?? existing.team1Id;
      const mergedTeam2 = data.team2Id ?? existing.team2Id;

      const pool = getPool();
      // Pull team names alongside the conflict row so the error
      // message can identify the exact match the admin is colliding
      // with — generic "uno de los equipos" wording leaves the admin
      // hunting through the schedule for the offender (especially
      // painful when a category filter on the FE hides the conflict
      // from the Cronograma grid).
      const conflictRes = await pool.query<{
        id: string;
        team1_id: string;
        team2_id: string;
        court: string;
        team1_name: string | null;
        team2_name: string | null;
      }>(
        `SELECT m.id, m.team1_id, m.team2_id, m.court,
                t1.name AS team1_name, t2.name AS team2_name
         FROM matches m
         LEFT JOIN teams t1 ON t1.id = m.team1_id
         LEFT JOIN teams t2 ON t2.id = m.team2_id
         WHERE m.tournament_id = $1
           AND m.id <> $2
           AND m.date = $3
           AND m.time = $4
           AND (
             m.team1_id = $5 OR m.team1_id = $6
             OR m.team2_id = $5 OR m.team2_id = $6
             OR m.court = $7
           )`,
        [
          mergedTournament,
          id,
          mergedDate,
          mergedTime,
          mergedTeam1,
          mergedTeam2,
          mergedCourt,
        ],
      );
      if (conflictRes.rows.length > 0) {
        // Compare team-vs-team only when BOTH sides are resolved.
        // Without the `!== null` guard, two unresolved bracket slots
        // sharing a court+time would be reported as a (false) team
        // collision instead of a court collision, because
        // `null === null` is true and the SQL row's team_id is also
        // null when materialized but unresolved.
        const teamConflict = conflictRes.rows.find(
          (r) =>
            (mergedTeam1 !== null &&
              (r.team1_id === mergedTeam1 || r.team2_id === mergedTeam1)) ||
            (mergedTeam2 !== null &&
              (r.team1_id === mergedTeam2 || r.team2_id === mergedTeam2)),
        );
        if (teamConflict) {
          const labelA = teamConflict.team1_name ?? 'Equipo 1';
          const labelB = teamConflict.team2_name ?? 'Equipo 2';
          throw new ValidationError(
            `Conflicto: a las ${mergedTime} ya está programado ${labelA} vs ${labelB} en ${teamConflict.court}. Uno de los equipos coincide.`,
          );
        }
        throw new ValidationError(
          `La cancha "${mergedCourt}" ya tiene un partido programado a las ${mergedTime}. Elegí otra cancha o cambiá el horario.`,
        );
      }
    }

    const pool = getPool();
    const fields: string[] = [];
    const values: unknown[] = [];
    let idx = 1;

    const columnMap: Record<string, string> = {
      tournamentId: 'tournament_id',
      team1Id: 'team1_id',
      team2Id: 'team2_id',
      date: 'date',
      time: 'time',
      court: 'court',
      referee: 'referee',
      status: 'status',
      scoreTeam1: 'score_team1',
      scoreTeam2: 'score_team2',
      phase: 'phase',
      groupName: 'group_name',
      duration: 'duration',
    };

    for (const [key, column] of Object.entries(columnMap)) {
      if ((data as Record<string, unknown>)[key] !== undefined) {
        fields.push(`${column} = $${idx}`);
        values.push((data as Record<string, unknown>)[key]);
        idx++;
      }
    }

    if (fields.length === 0) {
      return this.getById(id);
    }

    fields.push('updated_at = NOW()');
    values.push(id);

    const query = `UPDATE matches SET ${fields.join(', ')} WHERE id = $${idx} RETURNING *`;
    const result = await pool.query(query, values);

    // Recalculate standings if any field that affects them changed.
    // This catches admin edits that save scores / flip status / move a match
    // to a different group, none of which previously triggered the recalc.
    const standingsAffectingFields = [
      'status',
      'scoreTeam1',
      'scoreTeam2',
      'team1Id',
      'team2Id',
      'groupName',
      'tournamentId',
    ];
    const needsRecalc = standingsAffectingFields.some(
      (f) => (data as Record<string, unknown>)[f] !== undefined,
    );
    if (needsRecalc) {
      const tournamentId = (data.tournamentId ?? existing.tournamentId) as string;
      await refreshTournamentState(tournamentId);
    }

    // Mirror the score-update path: a bracket-stage match that just
    // flipped to `completed` from the admin form should still propagate
    // its winner to the next bracket round.
    if (existing.bracketMatchId && data.status === 'completed' && existing.status !== 'completed') {
      try {
        await bracketGenerator.syncBracketFromMatch(id);
      } catch (err) {
        console.warn('[update] syncBracketFromMatch failed:', err);
      }
    }

    // Fire a push when the admin flips a match into 'live' from here.
    // Score corrections from the admin form skip the score-push flow —
    // that belongs to the referee console where the judge drives scoring.
    if (data.status === 'live' && existing.status !== 'live') {
      ensurePushReady()
        .then((keys) => {
          if (!keys) return;
          return matchHeadline(id).then(({ title, url }) =>
            pushService.sendToAll({
              title: `${title} · En vivo`,
              body: '¡El partido acaba de comenzar!',
              url,
              tag: `match-live-${id}`,
              data: { matchId: id, type: 'match-live' },
            }),
          );
        })
        .catch((err) => console.warn('[push] match-live dispatch failed', err));
      // Same event, narrower audience: the captains of the two clubs
      // involved get a sharper "tu equipo está jugando ahora" cue.
      matchHeadline(id)
        .then(({ title, url }) =>
          dispatchClubsForMatch(id, {
            title: `${title} · En vivo`,
            body: 'Tu equipo está jugando ahora.',
            url,
            tag: `club-match-live-${id}`,
          }),
        )
        .catch((err) =>
          console.warn('[push] club match-live dispatch failed', err),
        );
    }

    // Schedule change notification — anytime the admin moves the
    // match to another (date, time, court) we ping the affected
    // clubs so their captains can re-plan transport / warm-up. The
    // notification fires for ANY one of those three fields, and
    // only when at least one of them actually changed (the previous
    // status-only edits don't qualify).
    const dateChanged =
      data.date !== undefined && data.date !== existing.date;
    const timeChanged =
      data.time !== undefined && data.time !== existing.time;
    const courtChanged =
      data.court !== undefined && data.court !== existing.court;
    if (dateChanged || timeChanged || courtChanged) {
      const finalDate = data.date ?? existing.date;
      const finalTime = data.time ?? existing.time;
      const finalCourt = data.court ?? existing.court;
      matchHeadline(id)
        .then(({ title, url }) =>
          dispatchClubsForMatch(id, {
            title: `${title} · Cambio de horario`,
            body: `Nuevo horario: ${finalDate} ${finalTime} · ${finalCourt}.`,
            url,
            tag: `club-match-schedule-${id}`,
          }),
        )
        .catch((err) =>
          console.warn('[push] club schedule-change dispatch failed', err),
        );
    }

    return mapRow(result.rows[0]);
  }

  /**
   * Atomically swap (date, time, court) between two matches. Used by
   * the Cronograma drag-and-drop UI when the admin drops match A on
   * the slot occupied by match B — neither plain UPDATE would succeed
   * standalone because each would crash into the other's row at the
   * service-level conflict check. The swap reads both originals first,
   * then issues two raw UPDATEs inside a transaction, bypassing the
   * per-row validation that powers the regular `update()` path.
   *
   * Constraints we DO enforce:
   *   · both matches must belong to the same tournament — admins can't
   *     accidentally move a match across tenants;
   *   · same tournament implies same ownership scope (the route is
   *     gated by `requireMatchAccess`).
   *
   * What we DON'T enforce (intentional):
   *   · team double-bookings against OTHER matches — we trust the FE
   *     to only swap pairs the admin actually picked, and the
   *     "Reparar horarios" tool exists for cleanup after the fact;
   *   · the (date, time) being inside the tournament window — admins
     *     can drag matches into days the schedule doesn't formally
   *     cover yet.
   * Both decisions favour flexibility — the admin sometimes needs to
   * test layouts before saving the new tournament window.
   */
  async swapSlots(matchAId: string, matchBId: string): Promise<{
    matchA: Match;
    matchB: Match;
  }> {
    if (matchAId === matchBId) {
      throw new ValidationError('Los IDs son iguales: no hay nada que intercambiar');
    }
    const pool = getPool();
    const client = await pool.connect();
    try {
      await client.query('BEGIN');
      // SELECT FOR UPDATE so a concurrent score write on either match
      // gets serialised after the swap commits, preventing the rare
      // race where two admins each drag the same card.
      const res = await client.query(
        `SELECT id, tournament_id, date::text AS date, time, court
           FROM matches
           WHERE id = ANY($1)
           FOR UPDATE`,
        [[matchAId, matchBId]],
      );
      if (res.rows.length !== 2) {
        throw new NotFoundError('Partido');
      }
      const rowA = res.rows.find((r) => r.id === matchAId);
      const rowB = res.rows.find((r) => r.id === matchBId);
      if (!rowA || !rowB) {
        throw new NotFoundError('Partido');
      }
      if (rowA.tournament_id !== rowB.tournament_id) {
        throw new ValidationError(
          'No se pueden intercambiar partidos de torneos distintos',
        );
      }
      // Apply A → B's slot and B → A's slot. The order doesn't matter
      // because the rows were already locked above; the two writes are
      // independent and Postgres will only commit both together.
      await client.query(
        `UPDATE matches SET date = $1, time = $2, court = $3, updated_at = NOW() WHERE id = $4`,
        [rowB.date, rowB.time, rowB.court, matchAId],
      );
      await client.query(
        `UPDATE matches SET date = $1, time = $2, court = $3, updated_at = NOW() WHERE id = $4`,
        [rowA.date, rowA.time, rowA.court, matchBId],
      );
      await client.query('COMMIT');
    } catch (err) {
      await client.query('ROLLBACK');
      throw err;
    } finally {
      client.release();
    }
    // Re-read both matches OUTSIDE the transaction so the returned
    // payload carries the full hydrated objects (with sets, etc.)
    // that the existing mapRow path produces.
    const [matchA, matchB] = await Promise.all([
      this.getById(matchAId),
      this.getById(matchBId),
    ]);
    // Notify both clubs about the slot swap — the captains see "tu
    // partido se movió" without having to refresh. Best-effort, runs
    // after COMMIT so a push failure never poisons the swap result.
    for (const m of [matchA, matchB]) {
      matchHeadline(m.id)
        .then(({ title, url }) =>
          dispatchClubsForMatch(m.id, {
            title: `${title} · Cambio de horario`,
            body: `Nuevo horario: ${m.date} ${m.time} · ${m.court}.`,
            url,
            tag: `club-match-schedule-${m.id}`,
          }),
        )
        .catch((err) =>
          console.warn('[push] swap club dispatch failed', err),
        );
    }
    return { matchA, matchB };
  }

  async updateScore(id: string, score: ScoreUpdate): Promise<Match> {
    // Ensure match exists
    const existing = await this.getById(id);
    const pool = getPool();

    // Validate set points are non-negative integers
    if (score.sets) {
      for (const set of score.sets) {
        if (!Number.isInteger(set.setNumber) || set.setNumber < 1 || set.setNumber > 5) {
          throw new ValidationError('El número de set debe ser un entero entre 1 y 5');
        }
        if (!Number.isInteger(set.team1Points) || set.team1Points < 0) {
          throw new ValidationError('Los puntos del equipo 1 deben ser un entero no negativo');
        }
        if (!Number.isInteger(set.team2Points) || set.team2Points < 0) {
          throw new ValidationError('Los puntos del equipo 2 deben ser un entero no negativo');
        }
      }
    }

    if (score.duration !== undefined && (score.duration <= 0 || !Number.isInteger(score.duration))) {
      throw new ValidationError('La duración debe ser un entero positivo');
    }

    // Update match fields
    const fields: string[] = [];
    const values: unknown[] = [];
    let idx = 1;

    if (score.status !== undefined) {
      fields.push(`status = $${idx}`);
      values.push(score.status);
      idx++;
    }
    if (score.scoreTeam1 !== undefined) {
      fields.push(`score_team1 = $${idx}`);
      values.push(score.scoreTeam1);
      idx++;
    }
    if (score.scoreTeam2 !== undefined) {
      fields.push(`score_team2 = $${idx}`);
      values.push(score.scoreTeam2);
      idx++;
    }
    if (score.duration !== undefined) {
      fields.push(`duration = $${idx}`);
      values.push(score.duration);
      idx++;
    }

    if (fields.length > 0) {
      fields.push('updated_at = NOW()');
      values.push(id);
      const query = `UPDATE matches SET ${fields.join(', ')} WHERE id = $${idx} RETURNING *`;
      await pool.query(query, values);
    }

    // Upsert sets and remove deleted ones
    if (score.sets) {
      if (score.sets.length > 0) {
        // Delete sets that are no longer in the list
        const setNumbers = score.sets.map(s => s.setNumber);
        await pool.query(
          'DELETE FROM set_scores WHERE match_id = $1 AND set_number != ALL($2)',
          [id, setNumbers]
        );
        for (const set of score.sets) {
          await pool.query(
            `INSERT INTO set_scores (match_id, set_number, team1_points, team2_points)
             VALUES ($1, $2, $3, $4)
             ON CONFLICT (match_id, set_number)
             DO UPDATE SET team1_points = $3, team2_points = $4`,
            [id, set.setNumber, set.team1Points, set.team2Points]
          );
        }
      } else {
        // Empty sets array means remove all sets
        await pool.query('DELETE FROM set_scores WHERE match_id = $1', [id]);
      }
    }

    // Recalculate standings whenever a score update touches anything that
    // affects them — set changes, score_team1/2 changes, status changes,
    // or any other field the referee / admin might edit. Previously we
    // only recalculated on the upcoming→completed transition, which meant
    // subsequent score corrections didn't update the table.
    const scoreTouched =
      score.sets !== undefined ||
      score.scoreTeam1 !== undefined ||
      score.scoreTeam2 !== undefined ||
      score.status !== undefined;
    if (scoreTouched) {
      await refreshTournamentState(existing.tournamentId);
    }

    // If this match is the materialization of a bracket slot and just
    // landed in `completed`, push the result back into the bracket
    // (records score, marks the bracket row completed, propagates the
    // winner to the next round). Idempotent — safe to call on every
    // score save; only triggers the actual advance once.
    if (existing.bracketMatchId && score.status === 'completed') {
      try {
        await bracketGenerator.syncBracketFromMatch(id);
      } catch (err) {
        console.warn('[updateScore] syncBracketFromMatch failed:', err);
      }
    }

    // Push dispatch (fire-and-forget):
    //   - status transitions to 'live'      → "En vivo" notification
    //   - a set just got decided            → "Set N cerrado" notification
    //   - status transitions to 'completed' → "Final" notification
    //
    // IMPORTANT: we count only DECIDED sets (one side ≥ 25 points with 2
    // of ventaja, or ≥ 15 with 2 in a 5th), NOT the raw array length.
    // The RefereeScore autosave now persists the in-progress set as the
    // last row in set_scores so the public + re-entry work correctly —
    // using `score.sets.length` here would fire a spurious "Set 1 cerrado"
    // on the very first point of every set, and skip real closures (the
    // array length stays the same between "Set 1 at 24-20" and "Set 1
    // closed at 25-20").
    const becameLive = score.status === 'live' && existing.status !== 'live';
    const becameCompleted = score.status === 'completed' && existing.status !== 'completed';
    const decidedSetsCount = (sets: Array<{ setNumber: number; team1Points: number; team2Points: number }> | undefined) => {
      if (!sets) return 0;
      let n = 0;
      for (const s of sets) {
        const target = s.setNumber >= 5 ? 15 : 25;
        const top = Math.max(s.team1Points, s.team2Points);
        const diff = Math.abs(s.team1Points - s.team2Points);
        if (top >= target && diff >= 2) n++;
      }
      return n;
    };
    const previousDecidedSets = decidedSetsCount(existing.sets);
    const newDecidedSets = decidedSetsCount(score.sets);
    const setJustClosed = newDecidedSets > previousDecidedSets;

    if (becameLive || becameCompleted || setJustClosed) {
      const notify = async () => {
        const keys = await ensurePushReady();
        if (!keys) return;
        const { title, url } = await matchHeadline(id);
        if (becameCompleted) {
          const setsH = (score.sets ?? []).filter((s) => s.team1Points > s.team2Points).length;
          const setsA = (score.sets ?? []).filter((s) => s.team2Points > s.team1Points).length;
          await pushService.sendToAll({
            title: `${title} · Final`,
            body: `Resultado ${setsH}–${setsA}. Tocá para ver el detalle.`,
            url,
            tag: `match-final-${id}`,
            data: { matchId: id, type: 'match-completed' },
          });
          // Same final, narrower audience: the two clubs get a
          // captain-specific notif. Done inside the same promise
          // chain so the `tag` collision isn't a concern (the
          // public tag and the club tag differ).
          await dispatchClubsForMatch(id, {
            title: `${title} · Final`,
            body: `Resultado ${setsH}–${setsA}. Tocá para ver el detalle.`,
            url,
            tag: `club-match-final-${id}`,
          });
          return;
        }
        if (setJustClosed && score.sets) {
          const last = score.sets[score.sets.length - 1];
          const setsH = score.sets.filter((s) => s.team1Points > s.team2Points).length;
          const setsA = score.sets.filter((s) => s.team2Points > s.team1Points).length;
          await pushService.sendToAll({
            title: `${title} · Set ${score.sets.length} cerrado`,
            body: `${last.team1Points}–${last.team2Points} · Sets ${setsH}–${setsA}`,
            url,
            tag: `match-score-${id}`,
            data: { matchId: id, type: 'set-closed' },
          });
          await dispatchClubsForMatch(id, {
            title: `${title} · Set ${score.sets.length} cerrado`,
            body: `${last.team1Points}–${last.team2Points} · Sets ${setsH}–${setsA}`,
            url,
            tag: `club-match-score-${id}`,
          });
          return;
        }
        if (becameLive) {
          await pushService.sendToAll({
            title: `${title} · En vivo`,
            body: '¡El partido acaba de comenzar!',
            url,
            tag: `match-live-${id}`,
            data: { matchId: id, type: 'match-live' },
          });
          await dispatchClubsForMatch(id, {
            title: `${title} · En vivo`,
            body: 'Tu equipo está jugando ahora.',
            url,
            tag: `club-match-live-${id}`,
          });
        }
      };
      notify().catch((err) => console.warn('[push] match dispatch failed', err));
    }

    return this.getById(id);
  }

  async delete(id: string): Promise<void> {
    // Snapshot the tournament id before the row is gone so we can
    // recalculate the standings once the match is out of the picture.
    const existing = await this.getById(id);
    const pool = getPool();
    // set_scores are deleted via CASCADE
    await pool.query('DELETE FROM matches WHERE id = $1', [id]);
    await refreshTournamentState(existing.tournamentId);
  }

  /**
   * Detect every team double-booking in a tournament and reschedule
   * the offending matches into safe slots. "Double-booking" here means:
   * the same team appears in two or more matches at the exact same
   * (date, time) — physically impossible because a team can only be on
   * one court at a time.
   *
   * Strategy:
   *   1. Pull every match in the tournament, sorted oldest-first.
   *   2. Walk them in order, tracking the (team, date, time) tuples
   *      already claimed.
   *   3. The first match for each (team, date, time) tuple keeps its
   *      slot; later matches that collide with it are flagged as
   *      "needs to move".
   *   4. For each one that needs to move: scan forward through the
   *      tournament's day window (08:00-18:00 by default, derived
   *      from the most recently used slot) and pick the next slot
   *      where:
   *         · neither team has another match,
   *         · the chosen court is free at that slot.
   *   5. UPDATE the row's date/time/court to the new slot. Leave
   *      everything else (status, scores, phase, group) untouched.
   *
   * Returns a summary so the caller can show the admin what was moved.
   *
   * The matches table is NOT locked during the scan — by design this is
   * a manual repair tool the admin runs from the UI; we want it
   * fast-running and tolerant of concurrent score updates rather than
   * a 30-second transaction holding everyone else off.
   */
  async repairTeamConflicts(
    tournamentId: string,
  ): Promise<{
    conflictsDetected: number;
    matchesMoved: number;
    /** Sub-totals so the UI can word the toast precisely. */
    teamConflicts: number;
    courtConflicts: number;
    outOfRange: number;
    /** Matches relocated only because the priority pass found them
     *  sitting in a slot that should belong to a higher-priority
     *  category. Distinct from team/court/oor conflicts. */
    priorityReordered: number;
    moves: Array<{
      matchId: string;
      from: { date: string; time: string; court: string };
      to: { date: string; time: string; court: string };
    }>;
    unresolved: number;
    /** Diagnostic block — surfaces what the repair "saw" so the admin
     *  console can debug edge cases (e.g. date-format mismatch) without
     *  needing access to Railway logs. */
    debug: {
      tournamentStart: string;
      tournamentEnd: string;
      totalMatches: number;
      earliestMatchDate: string | null;
      latestMatchDate: string | null;
    };
  }> {
    const pool = getPool();

    // Pull tournament context (start_date, end_date, courts, day window)
    // so the repair walks the same calendar the original scheduler uses
    // AND so we can detect matches that fall outside the tournament's
    // declared window (e.g. admin shifts start_date forward after fixtures
    // were generated → old matches now sit "before" the tournament).
    //
    // Both dates are cast to text in PG so we get plain 'YYYY-MM-DD'
    // strings instead of JS Date instances. Without this cast,
    // pg returns DATE columns as Date objects at LOCAL midnight, and
    // `.toISOString().slice(0, 10)` can return the previous day on a
    // server whose timezone is east of UTC. Casting to text inside the
    // query makes the value timezone-agnostic regardless of where the
    // server runs.
    const tRes = await pool.query<{
      start_date: string;
      end_date: string | null;
      courts: string[] | null;
      match_duration_minutes: number | null;
      match_break_minutes: number | null;
      daily_schedules: Record<string, { start: string; end: string }> | null;
      max_matches_per_day: number | null;
      dead_time_blocks: Array<{ start: string; end: string }> | null;
      category_priority: string[] | null;
    }>(
      `SELECT
         start_date::text AS start_date,
         end_date::text   AS end_date,
         courts,
         match_duration_minutes,
         match_break_minutes,
         daily_schedules,
         max_matches_per_day,
         dead_time_blocks,
         category_priority
       FROM tournaments WHERE id = $1`,
      [tournamentId],
    );
    if (tRes.rows.length === 0) {
      throw new NotFoundError('Torneo');
    }
    const courtsRow = tRes.rows[0].courts ?? [];
    const courts: string[] = courtsRow.length > 0 ? courtsRow : ['Cancha 1'];

    const tournamentStart = (tRes.rows[0].start_date ?? '').slice(0, 10);
    const tournamentEnd = (tRes.rows[0].end_date ?? tournamentStart).slice(0, 10);

    // Pull the tournament's persisted schedule defaults; fall back to
    // the historic numbers if a column is missing (legacy row, partial
    // SELECT, etc.). The per-day override map (`daily_schedules`) lets
    // each day use a different active window — see windowForDate below.
    const matchDurationMinutes = tRes.rows[0].match_duration_minutes ?? 60;
    const matchBreakMinutes = tRes.rows[0].match_break_minutes ?? 15;
    const dailySchedules = tRes.rows[0].daily_schedules ?? {};
    const SLOT_MIN = matchDurationMinutes + matchBreakMinutes;
    // Migration 025 constraints. 0 / empty means "no constraint" so the
    // repair falls back to the historic greedy behaviour when the admin
    // hasn't configured anything.
    const maxMatchesPerDay =
      typeof tRes.rows[0].max_matches_per_day === 'number' &&
      tRes.rows[0].max_matches_per_day > 0
        ? tRes.rows[0].max_matches_per_day
        : 0;
    const deadTimeBlocks = Array.isArray(tRes.rows[0].dead_time_blocks)
      ? tRes.rows[0].dead_time_blocks
      : [];
    // Empty array = "no priority configured" → keep matches in their
    // original order. When set, the repair will additionally reorder
    // every UPCOMING match so categories listed earlier take the
    // earliest slots — same semantics as the scheduler's pre-sort.
    const categoryPriority = Array.isArray(tRes.rows[0].category_priority)
      ? tRes.rows[0].category_priority
      : [];
    // Historic global window — used as the fallback for any day that
    // doesn't carry an explicit override in `dailySchedules`. Matches
    // the values the schedule modal showed before migration 024.
    const DEFAULT_DAY_START_MIN = 8 * 60; // 08:00
    const DEFAULT_DAY_END_MIN = 18 * 60; // 18:00

    /**
     * Resolve the active window for a given date, looking up
     * `daily_schedules['YYYY-MM-DD']` first and falling back to the
     * tournament-wide default. Returns minutes-from-midnight so the
     * slot-search loop can compare directly against `currentMinutes`.
     */
    const parseHHMM = (raw: string | undefined, fallback: number): number => {
      if (!raw) return fallback;
      const [h, m] = raw.split(':').map((n) => Number(n));
      if (!Number.isFinite(h) || !Number.isFinite(m)) return fallback;
      return h * 60 + m;
    };
    const windowForDate = (
      dateStr: string,
    ): { startMin: number; endMin: number } => {
      const override = dailySchedules[dateStr];
      return {
        startMin: parseHHMM(override?.start, DEFAULT_DAY_START_MIN),
        endMin: parseHHMM(override?.end, DEFAULT_DAY_END_MIN),
      };
    };

    // Pre-compute dead-time ranges in minutes-from-midnight so the
    // findFreeSlot inner loop can short-circuit cheaply. A candidate
    // slot is considered "dead" when its [start, start+matchDuration]
    // interval intersects ANY of the configured blocks.
    const deadRanges: Array<{ startMin: number; endMin: number }> = [];
    for (const block of deadTimeBlocks) {
      const s = parseHHMM(block.start, -1);
      const e = parseHHMM(block.end, -1);
      if (s >= 0 && e > s) deadRanges.push({ startMin: s, endMin: e });
    }
    const slotIntersectsDeadTime = (slotStartMin: number): boolean => {
      const slotEndMin = slotStartMin + matchDurationMinutes;
      for (const r of deadRanges) {
        if (slotStartMin < r.endMin && slotEndMin > r.startMin) return true;
      }
      return false;
    };

    // Pull every match, oldest first. created_at decides which match
    // "wins" the slot (oldest stays put) so the original schedule is
    // disturbed as little as possible.
    type Row = {
      id: string;
      team1_id: string;
      team2_id: string;
      date: string;
      time: string;
      court: string;
      created_at: string | Date;
      phase: string;
      status: 'upcoming' | 'live' | 'completed';
      group_name: string | null;
    };
    // Cast `date` to text so we get a stable YYYY-MM-DD string instead
    // of pg's JS Date instance (the driver normalises DATE columns to
    // Date objects which break our `${date}|${time}` cache keys).
    // `time` is already a VARCHAR(10) column ("14:00") so it travels
    // back as a plain string without any extra cast — using to_char
    // here would crash with "function to_char(character varying, …)
    // does not exist".
    //
    // Phase + status + group_name are pulled because the per-priority
    // reorder pass (when categoryPriority is set) needs to know which
    // category a match belongs to AND must skip live/completed matches
    // (they're already locked in or in flight; reshuffling them would
    // be hostile to the referee console).
    const allRes = await pool.query<Row>(
      `SELECT id, team1_id, team2_id,
              date::text AS date,
              time,
              court, created_at, phase, status, group_name
       FROM matches
       WHERE tournament_id = $1
       ORDER BY created_at ASC, id ASC`,
      [tournamentId],
    );
    const rows = allRes.rows;

    // Maps to track what's claimed:
    //   teamSlot   → "team|date|time"  → matchId
    //   courtSlot  → "court|date|time" → matchId
    const teamSlot = new Map<string, string>();
    const courtSlot = new Map<string, string>();
    const slotKey = (date: string, time: string) => `${date}|${time}`;
    const teamKey = (teamId: string, date: string, time: string) =>
      `${teamId}|${slotKey(date, time)}`;
    const courtKey = (court: string, date: string, time: string) =>
      `${court}|${slotKey(date, time)}`;

    // Two failure modes to detect, both surface the same way (the
    // match needs to move):
    //   1. Slot conflict — same team or court already busy at this
    //      (date, time). The earliest-inserted match keeps the slot,
    //      newer ones get queued for relocation.
    //   2. Out-of-range — match.date sits before tournament_start or
    //      after tournament_end. Happens when admin shifts the
    //      tournament dates after fixtures already exist.
    // Per-day counter seeded by the first pass so `findFreeSlot` can
    // honour the migration-025 `maxMatchesPerDay` cap without losing
    // track of matches that legitimately stayed in place. Bumping by
    // 1 per court-slot is correct because the court conflict logic
    // above already guarantees one row per (date, time, court).
    const matchesByDay = new Map<string, number>();
    const conflictMatches: Row[] = [];
    let teamConflicts = 0;
    let courtConflicts = 0;
    let outOfRange = 0;
    for (const r of rows) {
      const k1 = teamKey(r.team1_id, r.date, r.time);
      const k2 = teamKey(r.team2_id, r.date, r.time);
      const ck = courtKey(r.court, r.date, r.time);
      const teamHit = teamSlot.has(k1) || teamSlot.has(k2);
      const courtHit = courtSlot.has(ck);
      // Plain string comparison works because all three values are in
      // YYYY-MM-DD form (lexicographic order matches calendar order).
      const dateOutOfRange =
        tournamentStart !== '' &&
        (r.date < tournamentStart || r.date > tournamentEnd);
      // Time outside the day's active window — e.g. match at 16:00 on a
      // day whose dailySchedules entry says 08:00–14:00. Counts as out
      // of range so the repair pulls it back into a valid slot.
      const win = windowForDate(r.date);
      const matchMin = parseHHMM(r.time, -1);
      const timeOutOfWindow =
        matchMin >= 0 &&
        (matchMin < win.startMin || matchMin + matchDurationMinutes > win.endMin);
      // Match landed inside a configured dead-time block (e.g. 12:00
      // lunch) — treat the same as a window violation so the repair
      // pulls it out and finds a clean slot.
      const inDeadTime =
        matchMin >= 0 && slotIntersectsDeadTime(matchMin);
      const outsideWindow = dateOutOfRange || timeOutOfWindow || inDeadTime;
      if (teamHit || courtHit || outsideWindow) {
        conflictMatches.push(r);
        if (teamHit) teamConflicts++;
        else if (courtHit) courtConflicts++;
        if (outsideWindow) outOfRange++;
        continue;
      }
      teamSlot.set(k1, r.id);
      teamSlot.set(k2, r.id);
      courtSlot.set(ck, r.id);
      matchesByDay.set(r.date, (matchesByDay.get(r.date) ?? 0) + 1);
    }

    // Debug snapshot — emitted on every response so the admin tools (and
    // Railway logs) can verify the repair "saw" the right window even
    // when conflictsDetected ends up being 0.
    const sortedDates = rows
      .map((r) => r.date)
      .filter((d): d is string => typeof d === 'string')
      .sort();
    const debug = {
      tournamentStart,
      tournamentEnd,
      totalMatches: rows.length,
      earliestMatchDate: sortedDates[0] ?? null,
      latestMatchDate: sortedDates[sortedDates.length - 1] ?? null,
    };
    console.log(
      `[repair] tournament=${tournamentId} window=${tournamentStart}..${tournamentEnd} ` +
        `matches=${rows.length} conflicts=${conflictMatches.length} ` +
        `(team=${teamConflicts} court=${courtConflicts} oor=${outOfRange}) ` +
        `dates=${debug.earliestMatchDate}..${debug.latestMatchDate}`,
    );

    // Early-out only when there's nothing to repair AND no priority
    // reorder is pending. The priority pass below can ADD conflicts
    // (matches that aren't broken on their own but sit in the wrong
    // priority slot), so we must let it run before deciding the work
    // is done.
    if (conflictMatches.length === 0 && categoryPriority.length === 0) {
      return {
        conflictsDetected: 0,
        matchesMoved: 0,
        teamConflicts: 0,
        courtConflicts: 0,
        outOfRange: 0,
        priorityReordered: 0,
        moves: [],
        unresolved: 0,
        debug,
      };
    }

    // For each conflict, hunt for the next free slot. Start from the
    // tournament's first day at the day-window opening time, advancing
    // SLOT_MIN minutes per attempt and rolling to the next day at
    // 18:00. Cap at 365 days so a misconfigured tournament can't spin
    // forever. Naturally fills the earliest dates first so out-of-range
    // matches end up pulled INTO the tournament window when there's room.
    const startDate = tournamentStart || new Date().toISOString().slice(0, 10);

    const formatHHMM = (totalMinutes: number): string => {
      const h = Math.floor(totalMinutes / 60);
      const m = totalMinutes % 60;
      return `${String(h).padStart(2, '0')}:${String(m).padStart(2, '0')}`;
    };

    const findFreeSlot = (
      team1Id: string,
      team2Id: string,
    ): { date: string; time: string; court: string } | null => {
      const cursor = new Date(startDate + 'T00:00:00');
      const MAX_DAYS = 365;
      for (let d = 0; d < MAX_DAYS; d++) {
        const dateStr = cursor.toISOString().slice(0, 10);
        // Per-day cap (migration 025) — when the day already holds the
        // configured number of matches we skip it entirely instead of
        // probing slots that can't be used.
        if (
          maxMatchesPerDay > 0 &&
          (matchesByDay.get(dateStr) ?? 0) >= maxMatchesPerDay
        ) {
          cursor.setDate(cursor.getDate() + 1);
          continue;
        }
        // Each day's active window comes from the tournament's
        // `daily_schedules` map (with the historic 08:00–18:00 default
        // when the day isn't in the map). The match must FIT entirely
        // within that window, so the upper bound check uses the
        // tournament's configured match duration, not the slot stride.
        const { startMin, endMin } = windowForDate(dateStr);
        for (
          let mins = startMin;
          mins + matchDurationMinutes <= endMin;
          mins += SLOT_MIN
        ) {
          // Dead-time skip (migration 025). Slots whose body intersects
          // any configured block (lunch, ceremony, etc.) are unusable
          // regardless of team / court availability.
          if (slotIntersectsDeadTime(mins)) continue;
          const time = formatHHMM(mins);
          if (
            teamSlot.has(teamKey(team1Id, dateStr, time)) ||
            teamSlot.has(teamKey(team2Id, dateStr, time))
          ) {
            continue;
          }
          for (const court of courts) {
            if (!courtSlot.has(courtKey(court, dateStr, time))) {
              return { date: dateStr, time, court };
            }
          }
        }
        cursor.setDate(cursor.getDate() + 1);
      }
      return null;
    };

    /**
     * Priority reorder pass — only runs when the admin set
     * `categoryPriority`. The basic conflict detector above only
     * relocates matches that have a hard collision (team double-book,
     * court double-book, out-of-window). It doesn't enforce category
     * order: a low-priority match scheduled for 08:00 on day 1 stays
     * there even if a high-priority match is sitting at 17:00 on day
     * 3, which is exactly the bug the admin reported with
     * "Reparar horarios no hace nada" after changing priority.
     *
     * Strategy:
     *   1. Take every UPCOMING match still keeping its original slot
     *      (i.e. NOT already in conflictMatches).
     *   2. Sort them by category priority (lower index → earlier slot).
     *      Stable sort preserves their original order within each
     *      category so round-robin pairings keep their cadence.
     *   3. If the sorted order doesn't match the chronological order
     *      they're currently sitting in, mark the out-of-place ones as
     *      conflicts → they'll be moved by the existing loop below.
     *
     * Live + completed matches are NEVER touched: they're either being
     * scored right now or already locked in a referee's history.
     * Reshuffling them would surprise the judge console mid-set.
     */
    const extractCategory = (r: Row): string => {
      const raw = r.group_name || r.phase || '';
      const pipeIdx = raw.indexOf('|');
      return pipeIdx > 0 ? raw.slice(0, pipeIdx) : raw;
    };
    let priorityReordered = 0;
    if (categoryPriority.length > 0) {
      const priorityIndex = (cat: string): number => {
        const idx = categoryPriority.indexOf(cat);
        return idx >= 0 ? idx : categoryPriority.length;
      };
      // Pull out matches that DIDN'T conflict above and are still
      // upcoming. Sort them in slot order (date ASC, time ASC) so the
      // "current order" we compare against is what the admin would
      // actually see in the Cronograma view.
      const conflictIds = new Set(conflictMatches.map((r) => r.id));
      const upcomingPlaced = rows
        .filter((r) => !conflictIds.has(r.id) && r.status === 'upcoming')
        .sort((a, b) => {
          if (a.date !== b.date) return a.date < b.date ? -1 : 1;
          return a.time < b.time ? -1 : 1;
        });
      // Same list sorted by category priority (then by original
      // chronological position — stable sort preserves the round-robin
      // order for matches that share a priority bucket).
      const sortedByPriority = upcomingPlaced.slice().sort((a, b) => {
        const pa = priorityIndex(extractCategory(a));
        const pb = priorityIndex(extractCategory(b));
        return pa - pb;
      });
      // Walk the two lists in lockstep: any match that should sit on
      // a different slot than its current one is added to conflicts.
      // We also remove its busy markers from teamSlot/courtSlot so
      // findFreeSlot can hand its slot to a higher-priority match.
      for (let i = 0; i < upcomingPlaced.length; i++) {
        const inPlace = upcomingPlaced[i].id;
        const expected = sortedByPriority[i].id;
        if (inPlace !== expected) {
          // The match currently in slot[i] doesn't belong here per
          // priority. Eject it (clear busy markers + decrement day
          // counter) so the move loop can re-place it AND re-place
          // whatever should sit here instead.
          const r = upcomingPlaced[i];
          const k1 = teamKey(r.team1_id, r.date, r.time);
          const k2 = teamKey(r.team2_id, r.date, r.time);
          const ck = courtKey(r.court, r.date, r.time);
          if (teamSlot.get(k1) === r.id) teamSlot.delete(k1);
          if (teamSlot.get(k2) === r.id) teamSlot.delete(k2);
          if (courtSlot.get(ck) === r.id) courtSlot.delete(ck);
          const dayCount = matchesByDay.get(r.date) ?? 0;
          if (dayCount > 0) matchesByDay.set(r.date, dayCount - 1);
          conflictMatches.push(r);
          priorityReordered++;
        }
      }
      // Order the conflict list ascending by priority so the higher-
      // priority matches get findFreeSlot's earliest slots first.
      conflictMatches.sort(
        (a, b) =>
          priorityIndex(extractCategory(a)) -
          priorityIndex(extractCategory(b)),
      );
    }

    const moves: Array<{
      matchId: string;
      from: { date: string; time: string; court: string };
      to: { date: string; time: string; court: string };
    }> = [];
    let unresolved = 0;
    for (const r of conflictMatches) {
      const slot = findFreeSlot(r.team1_id, r.team2_id);
      if (!slot) {
        unresolved++;
        continue;
      }
      await pool.query(
        `UPDATE matches
         SET date = $1, time = $2, court = $3, updated_at = NOW()
         WHERE id = $4`,
        [slot.date, slot.time, slot.court, r.id],
      );
      teamSlot.set(teamKey(r.team1_id, slot.date, slot.time), r.id);
      teamSlot.set(teamKey(r.team2_id, slot.date, slot.time), r.id);
      courtSlot.set(courtKey(slot.court, slot.date, slot.time), r.id);
      // Track per-day count so subsequent findFreeSlot calls respect
      // the migration-025 cap. Without this bump, every conflict
      // could pile onto the same day even if the cap was set to 1.
      matchesByDay.set(slot.date, (matchesByDay.get(slot.date) ?? 0) + 1);
      moves.push({
        matchId: r.id,
        from: { date: r.date, time: r.time, court: r.court },
        to: slot,
      });
    }

    return {
      conflictsDetected: conflictMatches.length,
      matchesMoved: moves.length,
      teamConflicts,
      courtConflicts,
      outOfRange,
      priorityReordered,
      moves,
      unresolved,
      debug,
    };
  }

  async validateData(data: CreateMatchDto): Promise<ValidationResult> {
    validate(data as unknown as Record<string, unknown>, [
      { field: 'tournamentId', label: 'Torneo', required: true, type: 'string' },
      { field: 'team1Id', label: 'Equipo 1', required: true, type: 'string' },
      { field: 'team2Id', label: 'Equipo 2', required: true, type: 'string' },
      { field: 'date', label: 'Fecha', required: true, type: 'string' },
      { field: 'time', label: 'Hora', required: true, type: 'string' },
      { field: 'court', label: 'Cancha', required: true, type: 'string' },
      { field: 'phase', label: 'Fase', required: true, type: 'string' },
    ]);

    // Validate teams are different
    if (data.team1Id === data.team2Id) {
      throw new ValidationError('Los dos equipos deben ser diferentes');
    }

    // Validate tournament exists
    const pool = getPool();
    const tournamentCheck = await pool.query('SELECT id FROM tournaments WHERE id = $1', [data.tournamentId]);
    if (tournamentCheck.rows.length === 0) {
      throw new NotFoundError('Torneo');
    }

    // Validate team1 exists
    const team1Check = await pool.query('SELECT id FROM teams WHERE id = $1', [data.team1Id]);
    if (team1Check.rows.length === 0) {
      throw new NotFoundError('Equipo 1');
    }

    // Validate team2 exists
    const team2Check = await pool.query('SELECT id FROM teams WHERE id = $1', [data.team2Id]);
    if (team2Check.rows.length === 0) {
      throw new NotFoundError('Equipo 2');
    }

    return { valid: true, errors: [] };
  }

  // --- Private helpers ---

  private async getSets(matchId: string): Promise<SetScore[]> {
    const pool = getPool();
    const result = await pool.query(
      'SELECT * FROM set_scores WHERE match_id = $1 ORDER BY set_number',
      [matchId]
    );
    return result.rows.map(mapSetRow);
  }

  private async attachSets(matches: Match[]): Promise<Match[]> {
    if (matches.length === 0) return matches;
    const pool = getPool();
    const matchIds = matches.map(m => m.id);
    const result = await pool.query(
      'SELECT * FROM set_scores WHERE match_id = ANY($1) ORDER BY set_number',
      [matchIds]
    );
    const setsByMatch = new Map<string, SetScore[]>();
    for (const row of result.rows) {
      const set = mapSetRow(row);
      const existing = setsByMatch.get(set.matchId) || [];
      existing.push(set);
      setsByMatch.set(set.matchId, existing);
    }
    for (const match of matches) {
      match.sets = setsByMatch.get(match.id) || [];
    }
    return matches;
  }
}

export const matchService = new MatchService();
