import { getPool } from '../config/database';
import {
  Match,
  SetScore,
  CreateMatchDto,
  UpdateMatchDto,
  ScoreUpdate,
  ValidationResult,
} from '../types';
import { NotFoundError, ValidationError } from '../middleware/errorHandler';
import { validate } from '../middleware/validation';
import { standingsCalculator } from './standings.service';
import { bracketGenerator } from './bracket.service';
import { fixtureGenerator } from './fixture.service';
import { pushService, ensureReady as ensurePushReady } from './push.service';

/**
 * Fire-and-forget helper that builds the two-team label used in push
 * titles. Falls back to "Partido de voley" when we couldn't join the team
 * rows (shouldn't happen but a push should never fail a match write).
 */
async function matchHeadline(matchId: string): Promise<{ title: string; url: string }> {
  const pool = getPool();
  const result = await pool.query(
    `SELECT m.id, m.tournament_id,
            t1.name AS t1_name, t1.initials AS t1_initials,
            t2.name AS t2_name, t2.initials AS t2_initials
     FROM matches m
     LEFT JOIN teams t1 ON m.team1_id = t1.id
     LEFT JOIN teams t2 ON m.team2_id = t2.id
     WHERE m.id = $1`,
    [matchId],
  );
  if (result.rows.length === 0) {
    return { title: 'Partido de voley', url: '/' };
  }
  const row = result.rows[0];
  const team1 = (row.t1_name as string) || (row.t1_initials as string) || 'Equipo 1';
  const team2 = (row.t2_name as string) || (row.t2_initials as string) || 'Equipo 2';
  return {
    title: `${team1} vs ${team2}`,
    url: `/match/${matchId}`,
  };
}

/**
 * Recalculate standings and re-resolve any bracket placeholders for a
 * tournament. Called after every match mutation that could affect either.
 * Bracket re-resolution is wrapped in try/catch because it's best-effort:
 * tournaments without a bracket, or with bracket matches that have no
 * placeholders, should still succeed on the standings side.
 */
async function refreshTournamentState(tournamentId: string): Promise<void> {
  await standingsCalculator.recalculate(tournamentId);
  try {
    await bracketGenerator.resolveBracketFromStandings(tournamentId);
  } catch {
    // swallow — bracket refresh is best-effort
  }
  try {
    // Division-mode tournaments auto-seed Oro/Plata the moment every
    // group match for a category wraps up. The call is idempotent
    // (skips categories that already have a bracket), so running it
    // after every score write is safe and cheap.
    await fixtureGenerator.autoGenerateDivisionBrackets(tournamentId);
  } catch {
    // swallow — auto-bracket is best-effort, never blocks a score save
  }
  try {
    // Materialize playable matches for any bracket slot that just got
    // its two teams resolved (either by the standings re-resolution
    // above, or by a previous advanceWinner). Idempotent — only
    // creates rows for slots that don't yet have a `matches` row.
    await bracketGenerator.materializePendingBracketMatches(tournamentId);
  } catch (err) {
    console.warn('[refreshTournamentState] materialize failed:', err);
  }
}

function mapRow(row: Record<string, unknown>): Match {
  return {
    id: row.id as string,
    tournamentId: row.tournament_id as string,
    team1Id: row.team1_id as string,
    team2Id: row.team2_id as string,
    date: row.date as string,
    time: row.time as string,
    court: row.court as string,
    referee: row.referee as string | undefined,
    status: row.status as Match['status'],
    scoreTeam1: row.score_team1 != null ? (row.score_team1 as number) : undefined,
    scoreTeam2: row.score_team2 != null ? (row.score_team2 as number) : undefined,
    phase: row.phase as string,
    groupName: row.group_name as string | undefined,
    duration: row.duration != null ? (row.duration as number) : undefined,
    bracketMatchId: (row.bracket_match_id as string | null | undefined) ?? null,
    createdAt: row.created_at as string | undefined,
    updatedAt: row.updated_at as string | undefined,
  };
}

function mapSetRow(row: Record<string, unknown>): SetScore {
  return {
    id: row.id as string,
    matchId: row.match_id as string,
    setNumber: row.set_number as number,
    team1Points: row.team1_points as number,
    team2Points: row.team2_points as number,
  };
}

/**
 * Context used when listing matches. Public + super_admin see everything;
 * admins see matches of their own tournaments; judges see only LIVE
 * matches from tournaments owned by the admin that created them.
 */
export type MatchListScope =
  | { scope: 'all' }
  | { scope: 'owner'; ownerId: string }
  | { scope: 'judge'; judgeCreatedBy: string };

export class MatchService {
  async getAll(scope: MatchListScope = { scope: 'all' }): Promise<Match[]> {
    const pool = getPool();
    if (scope.scope === 'judge') {
      // Judges see only live matches from tournaments owned by the admin
      // who created them. The join with tournaments is how we enforce the
      // cross-tenant isolation in a single query instead of two round-trips.
      const result = await pool.query(
        `SELECT m.* FROM matches m
         JOIN tournaments t ON m.tournament_id = t.id
         WHERE t.owner_id = $1 AND m.status = 'live'
         ORDER BY m.date, m.time`,
        [scope.judgeCreatedBy],
      );
      const matches = result.rows.map(mapRow);
      return this.attachSets(matches);
    }
    if (scope.scope === 'owner') {
      const result = await pool.query(
        `SELECT m.* FROM matches m
         JOIN tournaments t ON m.tournament_id = t.id
         WHERE t.owner_id = $1
         ORDER BY m.date, m.time`,
        [scope.ownerId],
      );
      const matches = result.rows.map(mapRow);
      return this.attachSets(matches);
    }
    const result = await pool.query('SELECT * FROM matches ORDER BY date, time');
    const matches = result.rows.map(mapRow);
    return this.attachSets(matches);
  }

  async getById(id: string): Promise<Match> {
    const pool = getPool();
    const result = await pool.query('SELECT * FROM matches WHERE id = $1', [id]);
    if (result.rows.length === 0) {
      throw new NotFoundError('Partido');
    }
    const match = mapRow(result.rows[0]);
    const sets = await this.getSets(id);
    match.sets = sets;
    return match;
  }

  async getByTournament(tournamentId: string): Promise<Match[]> {
    // Verify tournament exists
    const pool = getPool();
    const tournamentCheck = await pool.query('SELECT id FROM tournaments WHERE id = $1', [tournamentId]);
    if (tournamentCheck.rows.length === 0) {
      throw new NotFoundError('Torneo');
    }
    const result = await pool.query(
      'SELECT * FROM matches WHERE tournament_id = $1 ORDER BY date, time',
      [tournamentId]
    );
    const matches = result.rows.map(mapRow);
    return this.attachSets(matches);
  }

  async create(data: CreateMatchDto): Promise<Match> {
    await this.validateData(data);
    const pool = getPool();
    const result = await pool.query(
      `INSERT INTO matches (tournament_id, team1_id, team2_id, date, time, court, referee, phase, group_name)
       VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
       RETURNING *`,
      [
        data.tournamentId,
        data.team1Id,
        data.team2Id,
        data.date,
        data.time,
        data.court,
        data.referee || null,
        data.phase,
        data.groupName || null,
      ]
    );
    return mapRow(result.rows[0]);
  }

  async update(id: string, data: UpdateMatchDto): Promise<Match> {
    // Ensure match exists
    const existing = await this.getById(id);

    // If updating team references, validate them
    if (data.team1Id !== undefined || data.team2Id !== undefined || data.tournamentId !== undefined) {
      const mergedTeam1 = data.team1Id ?? existing.team1Id;
      const mergedTeam2 = data.team2Id ?? existing.team2Id;
      const mergedTournament = data.tournamentId ?? existing.tournamentId;

      if (mergedTeam1 === mergedTeam2) {
        throw new ValidationError('Los dos equipos deben ser diferentes');
      }

      const pool = getPool();
      if (data.tournamentId !== undefined) {
        const tCheck = await pool.query('SELECT id FROM tournaments WHERE id = $1', [mergedTournament]);
        if (tCheck.rows.length === 0) {
          throw new NotFoundError('Torneo');
        }
      }
      if (data.team1Id !== undefined) {
        const t1Check = await pool.query('SELECT id FROM teams WHERE id = $1', [mergedTeam1]);
        if (t1Check.rows.length === 0) {
          throw new NotFoundError('Equipo 1');
        }
      }
      if (data.team2Id !== undefined) {
        const t2Check = await pool.query('SELECT id FROM teams WHERE id = $1', [mergedTeam2]);
        if (t2Check.rows.length === 0) {
          throw new NotFoundError('Equipo 2');
        }
      }
    }

    // Schedule conflict check — runs whenever the admin moves a match
    // (date / time / court change) OR swaps a team into a different
    // slot. We compare the would-be (date, time, team1, team2) against
    // every other match in the same tournament; if any of the four
    // pairings collide we abort with a human-readable error.
    //
    // Two failure modes we guard against:
    //   1. Same team plays two matches at the exact same date+time
    //      (the SAN JOSE A bug from 2026-05-10 — the algorithm got
    //      this right historically but a manual edit could put a team
    //      in two simultaneous matches without complaint).
    //   2. Two matches scheduled on the same court at the same date+time
    //      (court collision — physically impossible).
    //
    // Skipped only when none of the relevant fields are being touched
    // (purely a status / score / referee update) so editing scores on
    // an existing match never triggers a query just to re-confirm what
    // was already valid.
    const touchesSlot =
      data.date !== undefined ||
      data.time !== undefined ||
      data.court !== undefined ||
      data.team1Id !== undefined ||
      data.team2Id !== undefined ||
      data.tournamentId !== undefined;
    if (touchesSlot) {
      const mergedTournament = data.tournamentId ?? existing.tournamentId;
      const mergedDate = data.date ?? existing.date;
      const mergedTime = data.time ?? existing.time;
      const mergedCourt = data.court ?? existing.court;
      const mergedTeam1 = data.team1Id ?? existing.team1Id;
      const mergedTeam2 = data.team2Id ?? existing.team2Id;

      const pool = getPool();
      const conflictRes = await pool.query<{
        id: string;
        team1_id: string;
        team2_id: string;
        court: string;
      }>(
        `SELECT id, team1_id, team2_id, court
         FROM matches
         WHERE tournament_id = $1
           AND id <> $2
           AND date = $3
           AND time = $4
           AND (
             team1_id = $5 OR team1_id = $6
             OR team2_id = $5 OR team2_id = $6
             OR court = $7
           )`,
        [
          mergedTournament,
          id,
          mergedDate,
          mergedTime,
          mergedTeam1,
          mergedTeam2,
          mergedCourt,
        ],
      );
      if (conflictRes.rows.length > 0) {
        const teamConflict = conflictRes.rows.find(
          (r) =>
            r.team1_id === mergedTeam1 ||
            r.team1_id === mergedTeam2 ||
            r.team2_id === mergedTeam1 ||
            r.team2_id === mergedTeam2,
        );
        if (teamConflict) {
          throw new ValidationError(
            `Uno de los equipos ya tiene un partido programado el ${mergedDate} a las ${mergedTime}. Elegí otro horario.`,
          );
        }
        throw new ValidationError(
          `La cancha "${mergedCourt}" ya tiene un partido programado el ${mergedDate} a las ${mergedTime}. Elegí otra cancha o cambiá el horario.`,
        );
      }
    }

    const pool = getPool();
    const fields: string[] = [];
    const values: unknown[] = [];
    let idx = 1;

    const columnMap: Record<string, string> = {
      tournamentId: 'tournament_id',
      team1Id: 'team1_id',
      team2Id: 'team2_id',
      date: 'date',
      time: 'time',
      court: 'court',
      referee: 'referee',
      status: 'status',
      scoreTeam1: 'score_team1',
      scoreTeam2: 'score_team2',
      phase: 'phase',
      groupName: 'group_name',
      duration: 'duration',
    };

    for (const [key, column] of Object.entries(columnMap)) {
      if ((data as Record<string, unknown>)[key] !== undefined) {
        fields.push(`${column} = $${idx}`);
        values.push((data as Record<string, unknown>)[key]);
        idx++;
      }
    }

    if (fields.length === 0) {
      return this.getById(id);
    }

    fields.push('updated_at = NOW()');
    values.push(id);

    const query = `UPDATE matches SET ${fields.join(', ')} WHERE id = $${idx} RETURNING *`;
    const result = await pool.query(query, values);

    // Recalculate standings if any field that affects them changed.
    // This catches admin edits that save scores / flip status / move a match
    // to a different group, none of which previously triggered the recalc.
    const standingsAffectingFields = [
      'status',
      'scoreTeam1',
      'scoreTeam2',
      'team1Id',
      'team2Id',
      'groupName',
      'tournamentId',
    ];
    const needsRecalc = standingsAffectingFields.some(
      (f) => (data as Record<string, unknown>)[f] !== undefined,
    );
    if (needsRecalc) {
      const tournamentId = (data.tournamentId ?? existing.tournamentId) as string;
      await refreshTournamentState(tournamentId);
    }

    // Mirror the score-update path: a bracket-stage match that just
    // flipped to `completed` from the admin form should still propagate
    // its winner to the next bracket round.
    if (existing.bracketMatchId && data.status === 'completed' && existing.status !== 'completed') {
      try {
        await bracketGenerator.syncBracketFromMatch(id);
      } catch (err) {
        console.warn('[update] syncBracketFromMatch failed:', err);
      }
    }

    // Fire a push when the admin flips a match into 'live' from here.
    // Score corrections from the admin form skip the score-push flow —
    // that belongs to the referee console where the judge drives scoring.
    if (data.status === 'live' && existing.status !== 'live') {
      ensurePushReady()
        .then((keys) => {
          if (!keys) return;
          return matchHeadline(id).then(({ title, url }) =>
            pushService.sendToAll({
              title: `${title} · En vivo`,
              body: '¡El partido acaba de comenzar!',
              url,
              tag: `match-live-${id}`,
              data: { matchId: id, type: 'match-live' },
            }),
          );
        })
        .catch((err) => console.warn('[push] match-live dispatch failed', err));
    }

    return mapRow(result.rows[0]);
  }

  async updateScore(id: string, score: ScoreUpdate): Promise<Match> {
    // Ensure match exists
    const existing = await this.getById(id);
    const pool = getPool();

    // Validate set points are non-negative integers
    if (score.sets) {
      for (const set of score.sets) {
        if (!Number.isInteger(set.setNumber) || set.setNumber < 1 || set.setNumber > 5) {
          throw new ValidationError('El número de set debe ser un entero entre 1 y 5');
        }
        if (!Number.isInteger(set.team1Points) || set.team1Points < 0) {
          throw new ValidationError('Los puntos del equipo 1 deben ser un entero no negativo');
        }
        if (!Number.isInteger(set.team2Points) || set.team2Points < 0) {
          throw new ValidationError('Los puntos del equipo 2 deben ser un entero no negativo');
        }
      }
    }

    if (score.duration !== undefined && (score.duration <= 0 || !Number.isInteger(score.duration))) {
      throw new ValidationError('La duración debe ser un entero positivo');
    }

    // Update match fields
    const fields: string[] = [];
    const values: unknown[] = [];
    let idx = 1;

    if (score.status !== undefined) {
      fields.push(`status = $${idx}`);
      values.push(score.status);
      idx++;
    }
    if (score.scoreTeam1 !== undefined) {
      fields.push(`score_team1 = $${idx}`);
      values.push(score.scoreTeam1);
      idx++;
    }
    if (score.scoreTeam2 !== undefined) {
      fields.push(`score_team2 = $${idx}`);
      values.push(score.scoreTeam2);
      idx++;
    }
    if (score.duration !== undefined) {
      fields.push(`duration = $${idx}`);
      values.push(score.duration);
      idx++;
    }

    if (fields.length > 0) {
      fields.push('updated_at = NOW()');
      values.push(id);
      const query = `UPDATE matches SET ${fields.join(', ')} WHERE id = $${idx} RETURNING *`;
      await pool.query(query, values);
    }

    // Upsert sets and remove deleted ones
    if (score.sets) {
      if (score.sets.length > 0) {
        // Delete sets that are no longer in the list
        const setNumbers = score.sets.map(s => s.setNumber);
        await pool.query(
          'DELETE FROM set_scores WHERE match_id = $1 AND set_number != ALL($2)',
          [id, setNumbers]
        );
        for (const set of score.sets) {
          await pool.query(
            `INSERT INTO set_scores (match_id, set_number, team1_points, team2_points)
             VALUES ($1, $2, $3, $4)
             ON CONFLICT (match_id, set_number)
             DO UPDATE SET team1_points = $3, team2_points = $4`,
            [id, set.setNumber, set.team1Points, set.team2Points]
          );
        }
      } else {
        // Empty sets array means remove all sets
        await pool.query('DELETE FROM set_scores WHERE match_id = $1', [id]);
      }
    }

    // Recalculate standings whenever a score update touches anything that
    // affects them — set changes, score_team1/2 changes, status changes,
    // or any other field the referee / admin might edit. Previously we
    // only recalculated on the upcoming→completed transition, which meant
    // subsequent score corrections didn't update the table.
    const scoreTouched =
      score.sets !== undefined ||
      score.scoreTeam1 !== undefined ||
      score.scoreTeam2 !== undefined ||
      score.status !== undefined;
    if (scoreTouched) {
      await refreshTournamentState(existing.tournamentId);
    }

    // If this match is the materialization of a bracket slot and just
    // landed in `completed`, push the result back into the bracket
    // (records score, marks the bracket row completed, propagates the
    // winner to the next round). Idempotent — safe to call on every
    // score save; only triggers the actual advance once.
    if (existing.bracketMatchId && score.status === 'completed') {
      try {
        await bracketGenerator.syncBracketFromMatch(id);
      } catch (err) {
        console.warn('[updateScore] syncBracketFromMatch failed:', err);
      }
    }

    // Push dispatch (fire-and-forget):
    //   - status transitions to 'live'      → "En vivo" notification
    //   - a set just got decided            → "Set N cerrado" notification
    //   - status transitions to 'completed' → "Final" notification
    //
    // IMPORTANT: we count only DECIDED sets (one side ≥ 25 points with 2
    // of ventaja, or ≥ 15 with 2 in a 5th), NOT the raw array length.
    // The RefereeScore autosave now persists the in-progress set as the
    // last row in set_scores so the public + re-entry work correctly —
    // using `score.sets.length` here would fire a spurious "Set 1 cerrado"
    // on the very first point of every set, and skip real closures (the
    // array length stays the same between "Set 1 at 24-20" and "Set 1
    // closed at 25-20").
    const becameLive = score.status === 'live' && existing.status !== 'live';
    const becameCompleted = score.status === 'completed' && existing.status !== 'completed';
    const decidedSetsCount = (sets: Array<{ setNumber: number; team1Points: number; team2Points: number }> | undefined) => {
      if (!sets) return 0;
      let n = 0;
      for (const s of sets) {
        const target = s.setNumber >= 5 ? 15 : 25;
        const top = Math.max(s.team1Points, s.team2Points);
        const diff = Math.abs(s.team1Points - s.team2Points);
        if (top >= target && diff >= 2) n++;
      }
      return n;
    };
    const previousDecidedSets = decidedSetsCount(existing.sets);
    const newDecidedSets = decidedSetsCount(score.sets);
    const setJustClosed = newDecidedSets > previousDecidedSets;

    if (becameLive || becameCompleted || setJustClosed) {
      const notify = async () => {
        const keys = await ensurePushReady();
        if (!keys) return;
        const { title, url } = await matchHeadline(id);
        if (becameCompleted) {
          const setsH = (score.sets ?? []).filter((s) => s.team1Points > s.team2Points).length;
          const setsA = (score.sets ?? []).filter((s) => s.team2Points > s.team1Points).length;
          await pushService.sendToAll({
            title: `${title} · Final`,
            body: `Resultado ${setsH}–${setsA}. Tocá para ver el detalle.`,
            url,
            tag: `match-final-${id}`,
            data: { matchId: id, type: 'match-completed' },
          });
          return;
        }
        if (setJustClosed && score.sets) {
          const last = score.sets[score.sets.length - 1];
          const setsH = score.sets.filter((s) => s.team1Points > s.team2Points).length;
          const setsA = score.sets.filter((s) => s.team2Points > s.team1Points).length;
          await pushService.sendToAll({
            title: `${title} · Set ${score.sets.length} cerrado`,
            body: `${last.team1Points}–${last.team2Points} · Sets ${setsH}–${setsA}`,
            url,
            tag: `match-score-${id}`,
            data: { matchId: id, type: 'set-closed' },
          });
          return;
        }
        if (becameLive) {
          await pushService.sendToAll({
            title: `${title} · En vivo`,
            body: '¡El partido acaba de comenzar!',
            url,
            tag: `match-live-${id}`,
            data: { matchId: id, type: 'match-live' },
          });
        }
      };
      notify().catch((err) => console.warn('[push] match dispatch failed', err));
    }

    return this.getById(id);
  }

  async delete(id: string): Promise<void> {
    // Snapshot the tournament id before the row is gone so we can
    // recalculate the standings once the match is out of the picture.
    const existing = await this.getById(id);
    const pool = getPool();
    // set_scores are deleted via CASCADE
    await pool.query('DELETE FROM matches WHERE id = $1', [id]);
    await refreshTournamentState(existing.tournamentId);
  }

  /**
   * Detect every team double-booking in a tournament and reschedule
   * the offending matches into safe slots. "Double-booking" here means:
   * the same team appears in two or more matches at the exact same
   * (date, time) — physically impossible because a team can only be on
   * one court at a time.
   *
   * Strategy:
   *   1. Pull every match in the tournament, sorted oldest-first.
   *   2. Walk them in order, tracking the (team, date, time) tuples
   *      already claimed.
   *   3. The first match for each (team, date, time) tuple keeps its
   *      slot; later matches that collide with it are flagged as
   *      "needs to move".
   *   4. For each one that needs to move: scan forward through the
   *      tournament's day window (08:00-18:00 by default, derived
   *      from the most recently used slot) and pick the next slot
   *      where:
   *         · neither team has another match,
   *         · the chosen court is free at that slot.
   *   5. UPDATE the row's date/time/court to the new slot. Leave
   *      everything else (status, scores, phase, group) untouched.
   *
   * Returns a summary so the caller can show the admin what was moved.
   *
   * The matches table is NOT locked during the scan — by design this is
   * a manual repair tool the admin runs from the UI; we want it
   * fast-running and tolerant of concurrent score updates rather than
   * a 30-second transaction holding everyone else off.
   */
  async repairTeamConflicts(
    tournamentId: string,
  ): Promise<{
    conflictsDetected: number;
    matchesMoved: number;
    /** Sub-totals so the UI can word the toast precisely. */
    teamConflicts: number;
    courtConflicts: number;
    outOfRange: number;
    moves: Array<{
      matchId: string;
      from: { date: string; time: string; court: string };
      to: { date: string; time: string; court: string };
    }>;
    unresolved: number;
  }> {
    const pool = getPool();

    // Pull tournament context (start_date, end_date, courts, day window)
    // so the repair walks the same calendar the original scheduler uses
    // AND so we can detect matches that fall outside the tournament's
    // declared window (e.g. admin shifts start_date forward after fixtures
    // were generated → old matches now sit "before" the tournament).
    //
    // Both dates are cast to text in PG so we get plain 'YYYY-MM-DD'
    // strings instead of JS Date instances. Without this cast,
    // pg returns DATE columns as Date objects at LOCAL midnight, and
    // `.toISOString().slice(0, 10)` can return the previous day on a
    // server whose timezone is east of UTC. Casting to text inside the
    // query makes the value timezone-agnostic regardless of where the
    // server runs.
    const tRes = await pool.query<{
      start_date: string;
      end_date: string | null;
      courts: string[] | null;
    }>(
      `SELECT
         start_date::text AS start_date,
         end_date::text   AS end_date,
         courts
       FROM tournaments WHERE id = $1`,
      [tournamentId],
    );
    if (tRes.rows.length === 0) {
      throw new NotFoundError('Torneo');
    }
    const courtsRow = tRes.rows[0].courts ?? [];
    const courts: string[] = courtsRow.length > 0 ? courtsRow : ['Cancha 1'];

    const tournamentStart = (tRes.rows[0].start_date ?? '').slice(0, 10);
    const tournamentEnd = (tRes.rows[0].end_date ?? tournamentStart).slice(0, 10);

    const DAY_START_MIN = 8 * 60; // 08:00
    const DAY_END_MIN = 18 * 60; // 18:00
    const SLOT_MIN = 75; // 60 min match + 15 min break, mirrors the scheduler defaults

    // Pull every match, oldest first. created_at decides which match
    // "wins" the slot (oldest stays put) so the original schedule is
    // disturbed as little as possible.
    type Row = {
      id: string;
      team1_id: string;
      team2_id: string;
      date: string;
      time: string;
      court: string;
      created_at: string | Date;
    };
    // Cast `date` to text so we get a stable YYYY-MM-DD string instead
    // of pg's JS Date instance (the driver normalises DATE columns to
    // Date objects which break our `${date}|${time}` cache keys).
    // `time` is already a VARCHAR(10) column ("14:00") so it travels
    // back as a plain string without any extra cast — using to_char
    // here would crash with "function to_char(character varying, …)
    // does not exist".
    const allRes = await pool.query<Row>(
      `SELECT id, team1_id, team2_id,
              date::text AS date,
              time,
              court, created_at
       FROM matches
       WHERE tournament_id = $1
       ORDER BY created_at ASC, id ASC`,
      [tournamentId],
    );
    const rows = allRes.rows;

    // Maps to track what's claimed:
    //   teamSlot   → "team|date|time"  → matchId
    //   courtSlot  → "court|date|time" → matchId
    const teamSlot = new Map<string, string>();
    const courtSlot = new Map<string, string>();
    const slotKey = (date: string, time: string) => `${date}|${time}`;
    const teamKey = (teamId: string, date: string, time: string) =>
      `${teamId}|${slotKey(date, time)}`;
    const courtKey = (court: string, date: string, time: string) =>
      `${court}|${slotKey(date, time)}`;

    // Two failure modes to detect, both surface the same way (the
    // match needs to move):
    //   1. Slot conflict — same team or court already busy at this
    //      (date, time). The earliest-inserted match keeps the slot,
    //      newer ones get queued for relocation.
    //   2. Out-of-range — match.date sits before tournament_start or
    //      after tournament_end. Happens when admin shifts the
    //      tournament dates after fixtures already exist.
    const conflictMatches: Row[] = [];
    let teamConflicts = 0;
    let courtConflicts = 0;
    let outOfRange = 0;
    for (const r of rows) {
      const k1 = teamKey(r.team1_id, r.date, r.time);
      const k2 = teamKey(r.team2_id, r.date, r.time);
      const ck = courtKey(r.court, r.date, r.time);
      const teamHit = teamSlot.has(k1) || teamSlot.has(k2);
      const courtHit = courtSlot.has(ck);
      // Plain string comparison works because all three values are in
      // YYYY-MM-DD form (lexicographic order matches calendar order).
      const outsideWindow =
        tournamentStart !== '' &&
        (r.date < tournamentStart || r.date > tournamentEnd);
      if (teamHit || courtHit || outsideWindow) {
        conflictMatches.push(r);
        if (teamHit) teamConflicts++;
        else if (courtHit) courtConflicts++;
        if (outsideWindow) outOfRange++;
        continue;
      }
      teamSlot.set(k1, r.id);
      teamSlot.set(k2, r.id);
      courtSlot.set(ck, r.id);
    }

    if (conflictMatches.length === 0) {
      return {
        conflictsDetected: 0,
        matchesMoved: 0,
        teamConflicts: 0,
        courtConflicts: 0,
        outOfRange: 0,
        moves: [],
        unresolved: 0,
      };
    }

    // For each conflict, hunt for the next free slot. Start from the
    // tournament's first day at the day-window opening time, advancing
    // SLOT_MIN minutes per attempt and rolling to the next day at
    // 18:00. Cap at 365 days so a misconfigured tournament can't spin
    // forever. Naturally fills the earliest dates first so out-of-range
    // matches end up pulled INTO the tournament window when there's room.
    const startDate = tournamentStart || new Date().toISOString().slice(0, 10);

    const formatHHMM = (totalMinutes: number): string => {
      const h = Math.floor(totalMinutes / 60);
      const m = totalMinutes % 60;
      return `${String(h).padStart(2, '0')}:${String(m).padStart(2, '0')}`;
    };

    const findFreeSlot = (
      team1Id: string,
      team2Id: string,
    ): { date: string; time: string; court: string } | null => {
      const cursor = new Date(startDate + 'T00:00:00');
      const MAX_DAYS = 365;
      for (let d = 0; d < MAX_DAYS; d++) {
        const dateStr = cursor.toISOString().slice(0, 10);
        for (let mins = DAY_START_MIN; mins + 60 <= DAY_END_MIN; mins += SLOT_MIN) {
          const time = formatHHMM(mins);
          if (
            teamSlot.has(teamKey(team1Id, dateStr, time)) ||
            teamSlot.has(teamKey(team2Id, dateStr, time))
          ) {
            continue;
          }
          for (const court of courts) {
            if (!courtSlot.has(courtKey(court, dateStr, time))) {
              return { date: dateStr, time, court };
            }
          }
        }
        cursor.setDate(cursor.getDate() + 1);
      }
      return null;
    };

    const moves: Array<{
      matchId: string;
      from: { date: string; time: string; court: string };
      to: { date: string; time: string; court: string };
    }> = [];
    let unresolved = 0;
    for (const r of conflictMatches) {
      const slot = findFreeSlot(r.team1_id, r.team2_id);
      if (!slot) {
        unresolved++;
        continue;
      }
      await pool.query(
        `UPDATE matches
         SET date = $1, time = $2, court = $3, updated_at = NOW()
         WHERE id = $4`,
        [slot.date, slot.time, slot.court, r.id],
      );
      teamSlot.set(teamKey(r.team1_id, slot.date, slot.time), r.id);
      teamSlot.set(teamKey(r.team2_id, slot.date, slot.time), r.id);
      courtSlot.set(courtKey(slot.court, slot.date, slot.time), r.id);
      moves.push({
        matchId: r.id,
        from: { date: r.date, time: r.time, court: r.court },
        to: slot,
      });
    }

    return {
      conflictsDetected: conflictMatches.length,
      matchesMoved: moves.length,
      teamConflicts,
      courtConflicts,
      outOfRange,
      moves,
      unresolved,
    };
  }

  async validateData(data: CreateMatchDto): Promise<ValidationResult> {
    validate(data as unknown as Record<string, unknown>, [
      { field: 'tournamentId', label: 'Torneo', required: true, type: 'string' },
      { field: 'team1Id', label: 'Equipo 1', required: true, type: 'string' },
      { field: 'team2Id', label: 'Equipo 2', required: true, type: 'string' },
      { field: 'date', label: 'Fecha', required: true, type: 'string' },
      { field: 'time', label: 'Hora', required: true, type: 'string' },
      { field: 'court', label: 'Cancha', required: true, type: 'string' },
      { field: 'phase', label: 'Fase', required: true, type: 'string' },
    ]);

    // Validate teams are different
    if (data.team1Id === data.team2Id) {
      throw new ValidationError('Los dos equipos deben ser diferentes');
    }

    // Validate tournament exists
    const pool = getPool();
    const tournamentCheck = await pool.query('SELECT id FROM tournaments WHERE id = $1', [data.tournamentId]);
    if (tournamentCheck.rows.length === 0) {
      throw new NotFoundError('Torneo');
    }

    // Validate team1 exists
    const team1Check = await pool.query('SELECT id FROM teams WHERE id = $1', [data.team1Id]);
    if (team1Check.rows.length === 0) {
      throw new NotFoundError('Equipo 1');
    }

    // Validate team2 exists
    const team2Check = await pool.query('SELECT id FROM teams WHERE id = $1', [data.team2Id]);
    if (team2Check.rows.length === 0) {
      throw new NotFoundError('Equipo 2');
    }

    return { valid: true, errors: [] };
  }

  // --- Private helpers ---

  private async getSets(matchId: string): Promise<SetScore[]> {
    const pool = getPool();
    const result = await pool.query(
      'SELECT * FROM set_scores WHERE match_id = $1 ORDER BY set_number',
      [matchId]
    );
    return result.rows.map(mapSetRow);
  }

  private async attachSets(matches: Match[]): Promise<Match[]> {
    if (matches.length === 0) return matches;
    const pool = getPool();
    const matchIds = matches.map(m => m.id);
    const result = await pool.query(
      'SELECT * FROM set_scores WHERE match_id = ANY($1) ORDER BY set_number',
      [matchIds]
    );
    const setsByMatch = new Map<string, SetScore[]>();
    for (const row of result.rows) {
      const set = mapSetRow(row);
      const existing = setsByMatch.get(set.matchId) || [];
      existing.push(set);
      setsByMatch.set(set.matchId, existing);
    }
    for (const match of matches) {
      match.sets = setsByMatch.get(match.id) || [];
    }
    return matches;
  }
}

export const matchService = new MatchService();
